[package]
name = "jetpack"
version = "0.1.17"
edition = "2021"

[lib]
name = "jetpack"
path = "rust/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.5"
actix-web = "4.5.1"
mime = "0.3.17"
sha2 = "0.10.8"